# Generated by Django 4.0.5 on 2022-06-21 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exposure_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='노출종료일자'),
        ),
        migrations.AddField(
            model_name='article',
            name='exposure_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='노출시작일자'),
        ),
    ]
