# Generated by Django 4.0.5 on 2022-06-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory_product_detail_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_image',
            field=models.FileField(upload_to='uploads/detail/%Y/%m/%d/', verbose_name=''),
        ),
    ]
