# Generated by Django 4.0.5 on 2022-06-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_image',
            field=models.FileField(upload_to='uploads/detail/%Y/%m/%d/', verbose_name='상세이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(upload_to='uploads/thumbnail/%Y/%m/%d/', verbose_name='썸네일'),
        ),
    ]
