# Generated by Django 4.0.5 on 2022-06-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_detail_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일자'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='name',
            field=models.CharField(max_length=20, verbose_name='상품옵션명'),
        ),
    ]
