# Generated by Django 4.0.5 on 2022-06-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_register_date_alter_productoption_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_categoy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory', verbose_name='상품카테고리'),
        ),
    ]
